package ru.plumbum.tgrouter;

public enum UpdateType {
    MESSAGE_TEXT,
    MESSAGE_PHOTO,
    MESSAGE_VIDEO,
    MESSAGE_AUDIO,
    MESSAGE_VOICE,
    MESSAGE_DOCUMENT,
    MESSAGE_ANIMATION,
    MESSAGE_STICKER,
    MESSAGE_VIDEO_NOTE,
    MESSAGE_CONTACT,
    MESSAGE_LOCATION,
    MESSAGE_VENUE,
    MESSAGE_POLL,
    MESSAGE_DICE,
    MESSAGE_CAPTION,

    EDITED_MESSAGE_TEXT,
    EDITED_MESSAGE_CAPTION,

    CALLBACK_DATA,
    INLINE_QUERY,
    CHOSEN_INLINE_RESULT,
    SHIPPING_QUERY,
    PRE_CHECKOUT_QUERY,

    CHAT_MEMBER,
    MY_CHAT_MEMBER,
    CHAT_JOIN_REQUEST,

    ANY
}
